#!/bin/zsh
# Build LocalFlow.app in ~/Applications — a menu-bar app that runs localflow
# without a terminal window. Re-run after moving this repo.
set -e
REPO="$(cd "$(dirname "$0")" && pwd)"
APP="/Applications/LocalFlow.app"
[ -w /Applications ] || APP="$HOME/Applications/LocalFlow.app"

mkdir -p "$APP/Contents/MacOS"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>LocalFlow</string>
    <key>CFBundleDisplayName</key>     <string>LocalFlow</string>
    <key>CFBundleIdentifier</key>      <string>io.github.vin-l12.localflow</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundleExecutable</key>      <string>LocalFlow</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>LSUIElement</key>             <true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>LocalFlow records your voice while the hotkey is held, transcribes it on-device, and never sends audio anywhere.</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/LocalFlow" <<LAUNCHER
#!/bin/zsh
# Generated by make_app.sh — launches localflow headless, logs to ~/Library/Logs.
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
export PYTHONUNBUFFERED=1
exec >> "\$HOME/Library/Logs/localflow.log" 2>&1
echo "--- LocalFlow.app launch \$(date) ---"
cd "$REPO"
if [ ! -d .venv ]; then
    python3 -m venv .venv && .venv/bin/pip install -r requirements.txt
fi
exec .venv/bin/python localflow.py --app
LAUNCHER
chmod +x "$APP/Contents/MacOS/LocalFlow"

# ad-hoc signature: without one, macOS's permission grants to the bundle
# are fragile and can silently stop applying between launches
codesign --force --deep -s - "$APP"

echo "built $APP"
echo
echo "First launch: macOS will treat LocalFlow.app as a NEW app, so re-grant in"
echo "System Settings → Privacy & Security (add LocalFlow.app to each list):"
echo "  1. Microphone          (it will prompt on first dictation)"
echo "  2. Input Monitoring    (for the global hotkey)"
echo "  3. Accessibility       (for the synthetic Cmd-V paste)"
echo
echo "Optional — start at login: System Settings → General → Login Items → +"
